variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true -DskipTests=true"

build-generators:
  stage: build
  image: maven:3-jdk-11
  cache:
    paths:
      - .m2/repository
  script:
    - mvn package $MAVEN_CLI_OPTS
  artifacts:
    name: "Maven artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    paths:
      - "target/awesome-generators-1.0.0-jar-with-dependencies.jar"

build-docker-image:
  stage: deploy
  image: docker:20.10.16
  services:
    - docker:dind
  before_script:
    - mkdir -p $HOME/.docker
    - echo ${DOCKER_AUTH_CONFIG} > $HOME/.docker/config.json
  script:
    - docker buildx create --use
    - docker buildx build --push --platform linux/amd64,linux/arm64 -t registry.gitlab.com/model-taiwan/awesome-generators .
